image:
  tag: "v1.0.1"

replicaCount: 3

service:
  type: ClusterIP
  port: 80

serviceAccount:
  create: true
  name: ""
  automount: true
  annotations: {}

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50



